-- ============================================================
-- V1: Tenant infrastructure
-- ============================================================

CREATE TABLE tenants (
    id               VARCHAR(36)  NOT NULL,
    code             VARCHAR(50)  NOT NULL,
    name             VARCHAR(255) NOT NULL,
    legal_name       VARCHAR(255),
    address_line1    VARCHAR(255),
    address_line2    VARCHAR(255),
    city             VARCHAR(100),
    state_province   VARCHAR(100),
    postal_code      VARCHAR(20),
    country_code     CHAR(2),
    phone            VARCHAR(50),
    email            VARCHAR(255),
    website          VARCHAR(255),
    default_locale   VARCHAR(10)  NOT NULL DEFAULT 'en',
    default_currency CHAR(3)      NOT NULL DEFAULT 'USD',
    fiscal_year_start SMALLINT    NOT NULL DEFAULT 1,
    logo_path        VARCHAR(500),
    timezone         VARCHAR(100) NOT NULL DEFAULT 'UTC',
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    plan             VARCHAR(50)  NOT NULL DEFAULT 'trial',
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tenants PRIMARY KEY (id),
    CONSTRAINT uq_tenants_code UNIQUE (code)
);

CREATE TABLE tenant_messages (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   VARCHAR(36)  NOT NULL,
    locale      VARCHAR(10)  NOT NULL,
    message_key VARCHAR(255) NOT NULL,
    message_val TEXT         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tenant_messages PRIMARY KEY (id),
    CONSTRAINT fk_tenant_messages_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT uq_tenant_messages UNIQUE (tenant_id, locale, message_key)
);

CREATE TABLE number_sequences (
    id          BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   VARCHAR(36) NOT NULL,
    module      VARCHAR(50) NOT NULL,
    prefix      VARCHAR(20),
    year_in_seq BOOLEAN     NOT NULL DEFAULT TRUE,
    last_number BIGINT      NOT NULL DEFAULT 0,
    padding     SMALLINT    NOT NULL DEFAULT 4,
    CONSTRAINT pk_number_sequences PRIMARY KEY (id),
    CONSTRAINT fk_number_sequences_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT uq_number_sequences UNIQUE (tenant_id, module)
);

-- Seed: default tenant for development
INSERT INTO tenants (id, code, name, default_locale, default_currency, timezone, plan)
VALUES ('00000000-0000-0000-0000-000000000001', 'aplose', 'Aplose Demo', 'en', 'EUR', 'Europe/Paris', 'enterprise');
