-- ============================================================
-- V2: Security – users, roles, permissions
-- ============================================================

CREATE TABLE permissions (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code        VARCHAR(100) NOT NULL,
    module      VARCHAR(50)  NOT NULL,
    action      VARCHAR(50)  NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_permissions PRIMARY KEY (id),
    CONSTRAINT uq_permissions_code UNIQUE (code)
);

CREATE TABLE roles (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   VARCHAR(36)  NOT NULL,
    code        VARCHAR(100) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    is_system   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT fk_roles_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT uq_roles_tenant_code UNIQUE (tenant_id, code)
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permissions(id)
);

CREATE TABLE users (
    id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id           VARCHAR(36)  NOT NULL,
    username            VARCHAR(100) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    first_name          VARCHAR(100),
    last_name           VARCHAR(100),
    phone               VARCHAR(50),
    locale              VARCHAR(10),
    timezone            VARCHAR(100),
    avatar_path         VARCHAR(500),
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    is_tenant_admin     BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at       TIMESTAMP,
    password_changed_at TIMESTAMP,
    failed_login_count  SMALLINT     NOT NULL DEFAULT 0,
    locked_until        TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT uq_users_tenant_username UNIQUE (tenant_id, username),
    CONSTRAINT uq_users_tenant_email UNIQUE (tenant_id, email)
);

CREATE TABLE user_roles (
    user_id    BIGINT    NOT NULL,
    role_id    BIGINT    NOT NULL,
    granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by BIGINT,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE INDEX idx_users_tenant       ON users(tenant_id);
CREATE INDEX idx_roles_tenant       ON roles(tenant_id);

-- ============================================================
-- Seed: system permissions (full CRUD matrix)
-- ============================================================
INSERT INTO permissions (code, module, action, description) VALUES
  ('USER_CREATE',          'USER',          'CREATE',   'Create users'),
  ('USER_READ',            'USER',          'READ',     'View users'),
  ('USER_UPDATE',          'USER',          'UPDATE',   'Edit users'),
  ('USER_DELETE',          'USER',          'DELETE',   'Delete users'),
  ('USER_ADMIN',           'USER',          'ADMIN',    'Full user management'),
  ('ROLE_CREATE',          'ROLE',          'CREATE',   'Create roles'),
  ('ROLE_READ',            'ROLE',          'READ',     'View roles'),
  ('ROLE_UPDATE',          'ROLE',          'UPDATE',   'Edit roles'),
  ('ROLE_DELETE',          'ROLE',          'DELETE',   'Delete roles'),
  ('ROLE_ADMIN',           'ROLE',          'ADMIN',    'Full role management'),
  ('TENANT_READ',          'TENANT',        'READ',     'View tenant settings'),
  ('TENANT_UPDATE',        'TENANT',        'UPDATE',   'Edit tenant settings'),
  ('TENANT_ADMIN',         'TENANT',        'ADMIN',    'Full tenant administration'),
  ('THIRD_PARTY_CREATE',   'THIRD_PARTY',   'CREATE',   'Create third parties'),
  ('THIRD_PARTY_READ',     'THIRD_PARTY',   'READ',     'View third parties'),
  ('THIRD_PARTY_UPDATE',   'THIRD_PARTY',   'UPDATE',   'Edit third parties'),
  ('THIRD_PARTY_DELETE',   'THIRD_PARTY',   'DELETE',   'Delete third parties'),
  ('CONTACT_CREATE',       'CONTACT',       'CREATE',   'Create contacts'),
  ('CONTACT_READ',         'CONTACT',       'READ',     'View contacts'),
  ('CONTACT_UPDATE',       'CONTACT',       'UPDATE',   'Edit contacts'),
  ('CONTACT_DELETE',       'CONTACT',       'DELETE',   'Delete contacts'),
  ('PRODUCT_CREATE',       'PRODUCT',       'CREATE',   'Create products'),
  ('PRODUCT_READ',         'PRODUCT',       'READ',     'View products'),
  ('PRODUCT_UPDATE',       'PRODUCT',       'UPDATE',   'Edit products'),
  ('PRODUCT_DELETE',       'PRODUCT',       'DELETE',   'Delete products'),
  ('PROPOSAL_CREATE',      'PROPOSAL',      'CREATE',   'Create proposals'),
  ('PROPOSAL_READ',        'PROPOSAL',      'READ',     'View proposals'),
  ('PROPOSAL_UPDATE',      'PROPOSAL',      'UPDATE',   'Edit proposals'),
  ('PROPOSAL_DELETE',      'PROPOSAL',      'DELETE',   'Delete proposals'),
  ('PROPOSAL_APPROVE',     'PROPOSAL',      'APPROVE',  'Approve/send proposals'),
  ('SALES_ORDER_CREATE',   'SALES_ORDER',   'CREATE',   'Create sales orders'),
  ('SALES_ORDER_READ',     'SALES_ORDER',   'READ',     'View sales orders'),
  ('SALES_ORDER_UPDATE',   'SALES_ORDER',   'UPDATE',   'Edit sales orders'),
  ('SALES_ORDER_DELETE',   'SALES_ORDER',   'DELETE',   'Delete sales orders'),
  ('PURCHASE_ORDER_CREATE','PURCHASE_ORDER','CREATE',   'Create purchase orders'),
  ('PURCHASE_ORDER_READ',  'PURCHASE_ORDER','READ',     'View purchase orders'),
  ('PURCHASE_ORDER_UPDATE','PURCHASE_ORDER','UPDATE',   'Edit purchase orders'),
  ('PURCHASE_ORDER_DELETE','PURCHASE_ORDER','DELETE',   'Delete purchase orders'),
  ('INVOICE_CREATE',       'INVOICE',       'CREATE',   'Create invoices'),
  ('INVOICE_READ',         'INVOICE',       'READ',     'View invoices'),
  ('INVOICE_UPDATE',       'INVOICE',       'UPDATE',   'Edit invoices'),
  ('INVOICE_DELETE',       'INVOICE',       'DELETE',   'Delete invoices'),
  ('INVOICE_VALIDATE',     'INVOICE',       'VALIDATE', 'Validate/approve invoices'),
  ('PAYMENT_CREATE',       'PAYMENT',       'CREATE',   'Record payments'),
  ('PAYMENT_READ',         'PAYMENT',       'READ',     'View payments'),
  ('PAYMENT_DELETE',       'PAYMENT',       'DELETE',   'Delete payments'),
  ('CURRENCY_ADMIN',       'CURRENCY',      'ADMIN',    'Manage currencies and rates'),
  ('PROJECT_CREATE',       'PROJECT',       'CREATE',   'Create projects'),
  ('PROJECT_READ',         'PROJECT',       'READ',     'View projects'),
  ('PROJECT_UPDATE',       'PROJECT',       'UPDATE',   'Edit projects'),
  ('PROJECT_DELETE',       'PROJECT',       'DELETE',   'Delete projects'),
  ('TASK_CREATE',          'TASK',          'CREATE',   'Create tasks'),
  ('TASK_READ',            'TASK',          'READ',     'View tasks'),
  ('TASK_UPDATE',          'TASK',          'UPDATE',   'Edit tasks'),
  ('TASK_DELETE',          'TASK',          'DELETE',   'Delete tasks'),
  ('TIME_ENTRY_CREATE',    'TIME_ENTRY',    'CREATE',   'Log time entries'),
  ('TIME_ENTRY_READ',      'TIME_ENTRY',    'READ',     'View time entries'),
  ('TIME_ENTRY_UPDATE',    'TIME_ENTRY',    'UPDATE',   'Edit time entries'),
  ('TIME_ENTRY_DELETE',    'TIME_ENTRY',    'DELETE',   'Delete time entries'),
  ('AGENDA_CREATE',        'AGENDA',        'CREATE',   'Create events'),
  ('AGENDA_READ',          'AGENDA',        'READ',     'View events'),
  ('AGENDA_UPDATE',        'AGENDA',        'UPDATE',   'Edit events'),
  ('AGENDA_DELETE',        'AGENDA',        'DELETE',   'Delete events'),
  ('REPORT_READ',          'REPORT',        'READ',     'View reports'),
  ('REPORT_EXPORT',        'REPORT',        'EXPORT',   'Export reports');

-- ============================================================
-- Seed: default SUPER_ADMIN role for demo tenant
-- ============================================================
INSERT INTO roles (tenant_id, code, name, description, is_system)
VALUES ('00000000-0000-0000-0000-000000000001', 'SUPER_ADMIN', 'Super Administrator', 'Full access to all modules', TRUE);

-- Assign ALL permissions to SUPER_ADMIN
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.code = 'SUPER_ADMIN' AND r.tenant_id = '00000000-0000-0000-0000-000000000001';

-- Seed: default admin user (password: Admin1234!)
-- BCrypt hash of 'Admin1234!' with strength 12
INSERT INTO users (tenant_id, username, email, password_hash, first_name, last_name, is_active, is_tenant_admin)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'admin',
    'admin@aplose.fr',
    '$2a$12$OdQb9rvBWvIGlJFD5.YwmOCWmhh4CX/g9X5k5vH4J3z5z4R5z4R5.',
    'Admin',
    'Aplose',
    TRUE,
    TRUE
);

-- Assign SUPER_ADMIN role to admin user
INSERT INTO user_roles (user_id, role_id, granted_by)
SELECT u.id, r.id, u.id
FROM users u, roles r
WHERE u.username = 'admin'
  AND u.tenant_id = '00000000-0000-0000-0000-000000000001'
  AND r.code = 'SUPER_ADMIN'
  AND r.tenant_id = '00000000-0000-0000-0000-000000000001';
