-- ============================================================
-- V4: Catalog (products) and Currency
-- ============================================================

CREATE TABLE currencies (
    code           CHAR(3)     NOT NULL,
    name           VARCHAR(100) NOT NULL,
    symbol         VARCHAR(10)  NOT NULL,
    decimal_places SMALLINT     NOT NULL DEFAULT 2,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_currencies PRIMARY KEY (code)
);

CREATE TABLE exchange_rates (
    id            BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id     VARCHAR(36)   NOT NULL,
    from_currency CHAR(3)       NOT NULL,
    to_currency   CHAR(3)       NOT NULL,
    rate          NUMERIC(19,8) NOT NULL,
    rate_date     DATE          NOT NULL,
    source        VARCHAR(50)   NOT NULL DEFAULT 'MANUAL',
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_exchange_rates PRIMARY KEY (id),
    CONSTRAINT fk_er_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_er_from FOREIGN KEY (from_currency) REFERENCES currencies(code),
    CONSTRAINT fk_er_to   FOREIGN KEY (to_currency)   REFERENCES currencies(code),
    CONSTRAINT uq_exchange_rates UNIQUE (tenant_id, from_currency, to_currency, rate_date)
);

CREATE TABLE product_categories (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   VARCHAR(36)  NOT NULL,
    parent_id   BIGINT,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    sort_order  SMALLINT     NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_product_categories PRIMARY KEY (id),
    CONSTRAINT fk_pc_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_pc_parent FOREIGN KEY (parent_id) REFERENCES product_categories(id),
    CONSTRAINT uq_product_categories UNIQUE (tenant_id, code)
);

CREATE TABLE products (
    id                BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id         VARCHAR(36)   NOT NULL,
    category_id       BIGINT,
    code              VARCHAR(100)  NOT NULL,
    name              VARCHAR(255)  NOT NULL,
    description       TEXT,
    type              VARCHAR(20)   NOT NULL DEFAULT 'PRODUCT',
    unit_of_measure   VARCHAR(50),
    sale_price        NUMERIC(19,4) NOT NULL DEFAULT 0,
    purchase_price    NUMERIC(19,4) NOT NULL DEFAULT 0,
    currency_code     CHAR(3)       NOT NULL DEFAULT 'EUR',
    vat_rate          NUMERIC(6,4)  NOT NULL DEFAULT 0,
    is_sellable       BOOLEAN       NOT NULL DEFAULT TRUE,
    is_purchasable    BOOLEAN       NOT NULL DEFAULT TRUE,
    track_stock       BOOLEAN       NOT NULL DEFAULT FALSE,
    stock_quantity    NUMERIC(19,4) NOT NULL DEFAULT 0,
    stock_alert_level NUMERIC(19,4),
    barcode           VARCHAR(100),
    image_path        VARCHAR(500),
    notes             TEXT,
    is_active         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TIMESTAMP,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_tenant   FOREIGN KEY (tenant_id)   REFERENCES tenants(id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES product_categories(id),
    CONSTRAINT fk_products_currency FOREIGN KEY (currency_code) REFERENCES currencies(code),
    CONSTRAINT uq_products_tenant_code UNIQUE (tenant_id, code)
);

CREATE INDEX idx_products_tenant ON products(tenant_id);

-- Seed: common currencies
INSERT INTO currencies (code, name, symbol, decimal_places) VALUES
  ('EUR', 'Euro',                    '€', 2),
  ('USD', 'US Dollar',               '$', 2),
  ('GBP', 'British Pound',           '£', 2),
  ('CHF', 'Swiss Franc',             'Fr',2),
  ('JPY', 'Japanese Yen',            '¥', 0),
  ('CAD', 'Canadian Dollar',         'C$',2),
  ('AUD', 'Australian Dollar',       'A$',2),
  ('MAD', 'Moroccan Dirham',         'د.م.',2),
  ('TND', 'Tunisian Dinar',          'د.ت',3),
  ('DZD', 'Algerian Dinar',          'د.ج',2),
  ('XOF', 'West African CFA Franc',  'CFA',0),
  ('XAF', 'Central African CFA Franc','FCFA',0);
