-- ============================================================
-- V6: Project management and Agenda
-- ============================================================

CREATE TABLE projects (
    id             BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id      VARCHAR(36)   NOT NULL,
    code           VARCHAR(50)   NOT NULL,
    name           VARCHAR(255)  NOT NULL,
    description    TEXT,
    third_party_id BIGINT,
    status         VARCHAR(30)   NOT NULL DEFAULT 'PLANNING',
    priority       VARCHAR(20)   NOT NULL DEFAULT 'MEDIUM',
    date_start     DATE,
    date_end       DATE,
    budget_amount  NUMERIC(19,4),
    currency_code  CHAR(3),
    manager_id     BIGINT,
    billing_mode   VARCHAR(30)   DEFAULT 'FIXED',
    notes          TEXT,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     BIGINT,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_proj_tenant   FOREIGN KEY (tenant_id)      REFERENCES tenants(id),
    CONSTRAINT fk_proj_tp       FOREIGN KEY (third_party_id) REFERENCES third_parties(id),
    CONSTRAINT fk_proj_currency FOREIGN KEY (currency_code)  REFERENCES currencies(code),
    CONSTRAINT fk_proj_manager  FOREIGN KEY (manager_id)     REFERENCES users(id),
    CONSTRAINT uq_projects_code UNIQUE (tenant_id, code)
);

CREATE TABLE project_members (
    project_id BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    role       VARCHAR(50) NOT NULL DEFAULT 'MEMBER',
    joined_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_project_members PRIMARY KEY (project_id, user_id),
    CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_pm_user    FOREIGN KEY (user_id)    REFERENCES users(id)
);

CREATE TABLE project_tasks (
    id             BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id      VARCHAR(36)  NOT NULL,
    project_id     BIGINT       NOT NULL,
    parent_task_id BIGINT,
    title          VARCHAR(255) NOT NULL,
    description    TEXT,
    status         VARCHAR(30)  NOT NULL DEFAULT 'TODO',
    priority       VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    assigned_to_id BIGINT,
    date_start     DATE,
    date_due       DATE,
    date_completed DATE,
    estimated_hours NUMERIC(8,2),
    logged_hours    NUMERIC(8,2) NOT NULL DEFAULT 0,
    progress_pct   SMALLINT     NOT NULL DEFAULT 0,
    sort_order     SMALLINT     NOT NULL DEFAULT 0,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_project_tasks PRIMARY KEY (id),
    CONSTRAINT fk_pt_tenant      FOREIGN KEY (tenant_id)      REFERENCES tenants(id),
    CONSTRAINT fk_pt_project     FOREIGN KEY (project_id)     REFERENCES projects(id),
    CONSTRAINT fk_pt_parent      FOREIGN KEY (parent_task_id) REFERENCES project_tasks(id),
    CONSTRAINT fk_pt_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES users(id)
);

CREATE TABLE time_entries (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id       VARCHAR(36)  NOT NULL,
    task_id         BIGINT,
    project_id      BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    date_worked     DATE         NOT NULL,
    hours           NUMERIC(8,2) NOT NULL,
    description     TEXT,
    is_billable     BOOLEAN      NOT NULL DEFAULT TRUE,
    invoice_line_id BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_time_entries PRIMARY KEY (id),
    CONSTRAINT fk_te_tenant  FOREIGN KEY (tenant_id)  REFERENCES tenants(id),
    CONSTRAINT fk_te_task    FOREIGN KEY (task_id)    REFERENCES project_tasks(id),
    CONSTRAINT fk_te_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_te_user    FOREIGN KEY (user_id)    REFERENCES users(id)
);

CREATE TABLE agenda_events (
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id       VARCHAR(36)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    type            VARCHAR(30)  NOT NULL DEFAULT 'MEETING',
    status          VARCHAR(20)  NOT NULL DEFAULT 'PLANNED',
    all_day         BOOLEAN      NOT NULL DEFAULT FALSE,
    start_datetime  TIMESTAMP    NOT NULL,
    end_datetime    TIMESTAMP,
    location        VARCHAR(500),
    organizer_id    BIGINT       NOT NULL,
    third_party_id  BIGINT,
    contact_id      BIGINT,
    project_id      BIGINT,
    recurrence_rule VARCHAR(500),
    recurrence_end  DATE,
    parent_event_id BIGINT,
    color           VARCHAR(7),
    is_private      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_agenda_events PRIMARY KEY (id),
    CONSTRAINT fk_ae_tenant      FOREIGN KEY (tenant_id)     REFERENCES tenants(id),
    CONSTRAINT fk_ae_organizer   FOREIGN KEY (organizer_id)  REFERENCES users(id),
    CONSTRAINT fk_ae_tp          FOREIGN KEY (third_party_id) REFERENCES third_parties(id),
    CONSTRAINT fk_ae_contact     FOREIGN KEY (contact_id)    REFERENCES contacts(id),
    CONSTRAINT fk_ae_project     FOREIGN KEY (project_id)    REFERENCES projects(id),
    CONSTRAINT fk_ae_parent      FOREIGN KEY (parent_event_id) REFERENCES agenda_events(id)
);

CREATE TABLE agenda_event_attendees (
    id         BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_id   BIGINT      NOT NULL,
    user_id    BIGINT,
    contact_id BIGINT,
    status     VARCHAR(20) NOT NULL DEFAULT 'INVITED',
    notified_at TIMESTAMP,
    CONSTRAINT pk_agenda_event_attendees PRIMARY KEY (id),
    CONSTRAINT fk_aea_event   FOREIGN KEY (event_id)   REFERENCES agenda_events(id),
    CONSTRAINT fk_aea_user    FOREIGN KEY (user_id)    REFERENCES users(id),
    CONSTRAINT fk_aea_contact FOREIGN KEY (contact_id) REFERENCES contacts(id)
);

CREATE TABLE audit_log (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   VARCHAR(36)  NOT NULL,
    user_id     BIGINT,
    username    VARCHAR(100),
    ip_address  VARCHAR(45),
    action      VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id   VARCHAR(100),
    old_values  TEXT,
    new_values  TEXT,
    occurred_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_log PRIMARY KEY (id)
);

CREATE INDEX idx_projects_tenant     ON projects(tenant_id);
CREATE INDEX idx_project_tasks_tenant ON project_tasks(tenant_id, project_id);
CREATE INDEX idx_agenda_events_range  ON agenda_events(tenant_id, start_datetime, end_datetime);
CREATE INDEX idx_audit_log_entity     ON audit_log(tenant_id, entity_type, entity_id);
