-- ============================================================
-- V7: Extrafields (custom fields) and Field Visibility Config
-- ============================================================

-- Extrafield definitions: admin-defined custom fields per entity type
CREATE TABLE extrafield_definitions (
    id               BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id        VARCHAR(36)  NOT NULL,
    entity_type      VARCHAR(50)  NOT NULL,
    field_code       VARCHAR(50)  NOT NULL,
    label            VARCHAR(255) NOT NULL,
    field_type       VARCHAR(30)  NOT NULL,
    field_options    TEXT,
    default_value    VARCHAR(500),
    is_required      BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order       SMALLINT     NOT NULL DEFAULT 0,
    visible_on_list  BOOLEAN      NOT NULL DEFAULT FALSE,
    visible_on_detail BOOLEAN     NOT NULL DEFAULT TRUE,
    visible_on_form  BOOLEAN      NOT NULL DEFAULT TRUE,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_extrafield_definitions PRIMARY KEY (id),
    CONSTRAINT fk_efd_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT uq_efd_tenant_entity_code UNIQUE (tenant_id, entity_type, field_code)
);

CREATE INDEX idx_efd_tenant_entity ON extrafield_definitions(tenant_id, entity_type);

-- Extrafield values: EAV storage for custom field data
CREATE TABLE extrafield_values (
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   VARCHAR(36)  NOT NULL,
    entity_type VARCHAR(50)  NOT NULL,
    entity_id   BIGINT       NOT NULL,
    field_code  VARCHAR(50)  NOT NULL,
    value_text  TEXT,
    CONSTRAINT pk_extrafield_values PRIMARY KEY (id),
    CONSTRAINT fk_efv_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT uq_efv_entity_field UNIQUE (tenant_id, entity_type, entity_id, field_code)
);

CREATE INDEX idx_efv_entity ON extrafield_values(tenant_id, entity_type, entity_id);

-- Field visibility configuration: control which standard fields appear on views
CREATE TABLE field_visibility_config (
    id                BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_id         VARCHAR(36)  NOT NULL,
    entity_type       VARCHAR(50)  NOT NULL,
    field_name        VARCHAR(100) NOT NULL,
    visible_on_list   BOOLEAN      NOT NULL DEFAULT TRUE,
    visible_on_detail BOOLEAN      NOT NULL DEFAULT TRUE,
    visible_on_form   BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order        SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT pk_field_visibility_config PRIMARY KEY (id),
    CONSTRAINT fk_fvc_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT uq_fvc_tenant_entity_field UNIQUE (tenant_id, entity_type, field_name)
);

CREATE INDEX idx_fvc_tenant_entity ON field_visibility_config(tenant_id, entity_type);

-- New permissions
INSERT INTO permissions (code, module, action, description) VALUES
  ('EXTRAFIELD_ADMIN',    'EXTRAFIELD',    'ADMIN', 'Manage custom extra fields'),
  ('FIELD_CONFIG_ADMIN',  'FIELD_CONFIG',  'ADMIN', 'Manage field visibility configuration');

-- Assign new permissions to SUPER_ADMIN role
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.code = 'SUPER_ADMIN'
  AND r.tenant_id = '00000000-0000-0000-0000-000000000001'
  AND p.code IN ('EXTRAFIELD_ADMIN', 'FIELD_CONFIG_ADMIN');
